### ISSUE TITLE
TESTING: Traktor Kontrol S4 Mk2 Testing Offer

### ISSUE THREAD

**Issue by rushowr** [terminar/rebellion#4]
Hello, I'd like to offer up testing with my Traktor Kontrol S4 mk2. Do you have a structured list of testing items I could refer to in order to ensure I test _**everything**_? If there isn't a list already, would you be willing to create one? I'd be willing to assist on that as well. There's three reasons why I ask this ahead of time: 
1. I've had memory issues ever since a traumatic brain injury and lists are very handy to me (and honestly _everyone_) to make sure nothing is missed. 
2.  When confronted with testing a piece of software and having only the missive of "test everything to make sure it works", the task of performing the testing can seem overwhelming. Having a list as being discussed helps to add focus and alleviate the feeling of being overwhelmed.
3. A test item list will ensure uniformity between testers and test devices (obviously devices will differ to some degree, but the functionality tests should be the same at a base level with extraneous functionality (like the Traktor Kontrol jog wheels and items pertaining to decks in the case of the S4) put into sections dedicated to specific devices.
I hope you get that I'm only asking, and mean no offense. Additionally, I'm willing to work on the testing list as well, I just wanted to ask before pulling a fork and starting on anything before checking to see if it preexisted elsewhere or was in the works but not yet merged in.

I look forward to hearing from you and to testing all of this out!

**Comment by terminar** [comment]
Hey,
sorry for the late answer - currently the project is "halted" due to several things happening at NI and some personal interests. Also there is not really a big interest by other developers to work together on this stuff. 
When I pick up the development again and need testing, i'll add some information to the README.md/the github.

Thank you for interest in the project.
